name: PublishTests

on:
  release:
    types: [published]

jobs:
#  autoformatting:
#    uses: ./.github/workflows/autoformatting.yml
#  testing:
#    needs: autoformatting
#    uses: ./.github/workflows/testing.yml
  publish:
#    needs: testing
    uses: ./.github/workflows/uploadpypi.yml
    secrets: inherit
